### ISSUE TITLE
x_mitre_system_requirements type is string[], not 'string'

### ISSUE THREAD

**Issue by rivantsov** [mitre-attack/attack-stix-data#4]
file Usage.md, section Techniques:
https://github.com/mitre-attack/attack-stix-data/blob/master/USAGE.md#techniques

The type for element x_mitre_system_requirements should be string[] (string array instead of string).
At least according to actual data inside data files

**Comment by isaisabel** [comment]
Thanks for pointing this out! It looks like the USAGE document on this repo has fallen out of date compared to that on MITRE/CTI, which already includes this fix (and lists additional fields for techniques): https://github.com/mitre/cti/blob/master/USAGE.md#techniques
