### ISSUE TITLE
Duplicate data source value in attack pattern

### ISSUE THREAD

**Issue by rivantsov** [mitre-attack/attack-stix-data#5]
enterprise file, attack pattern with ID: 

attack-pattern--035bb001-ab69-4a0b-9f6c-2de8b09e1b9d

property x_mitre_data_sources, value 'Network Traffic Flow' repeated twice

**Comment by isaisabel** [comment]
This issue will be fixed in the next release of ATT&CK (ATT&CK v10). We don't typically patch the content of previous ATT&CK releases so the bug will persist in ATT&CK v9.
